/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>


#ifndef _Included_com_easyrtc_Peer
#define _Included_com_easyrtc_Peer


#define JNI_VERSION JNI_VERSION_1_4
#include <android/log.h>


#ifdef __cplusplus
extern "C" {
#endif

extern JavaVM *g_vm;
#if 1//def __DEBUG__
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG  , "EASYDARWIN", __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR  , "EASYDARWIN", __VA_ARGS__)
#else
#define LOGD(...)
#define LOGE(...)
#endif



// 函数说明:    创建PeerConnection  返回peerconnection, 连接状态回调函数如下:
//              public static int OnEasyRTC_ConnectionStateChange_Callback(long userPtr, int state) 
//              {
//                  state 值如下:
//                          EASYRTC_PEER_CONNECTION_STATE_NONE = 0,         // 初始状态
//                          EASYRTC_PEER_CONNECTION_STATE_NEW = 1,          // 当ICE代理等待远程凭证时设置此状态
//                          EASYRTC_PEER_CONNECTION_STATE_CONNECTING = 2,   // 当ICE代理检查连接时设置此状态
//                          EASYRTC_PEER_CONNECTION_STATE_CONNECTED = 3,    // 当ICE代理就绪时设置此状态
//                          EASYRTC_PEER_CONNECTION_STATE_DISCONNECTED = 4, // 当ICE代理断开连接时设置此状态
//                          EASYRTC_PEER_CONNECTION_STATE_FAILED = 5,       // 当ICE代理转换为失败状态时设置此状态
//                          EASYRTC_PEER_CONNECTION_STATE_CLOSED = 6,       // 此状态导致流会话终止
//                          EASYRTC_PEER_CONNECTION_TOTAL_STATE_COUNT = 7,  // 此状态表示对等连接状态的最大数量
//              }
// 输入:
//          iceTransportPolicy: 
//                              EasyRTC_ICE_TRANSPORT_POLICY_RELAY = 1, // ICE代理只使用媒体中继
//                              EasyRTC_ICE_TRANSPORT_POLICY_ALL = 2,   // ICE代理使用任何类型的候选

//          stun_server_url:    stun服务器地址
//          turn_server_url:    turn服务器地址
//          turn_username:      turn服务器用户名
//          turn_credential:    turn服务器密码
//          userptr:            用户自定义值，用于在回调时原样回调
// 输出:  
//          PeerConnection
JNIEXPORT jlong JNICALL Java_cn_easyrtc_peerconnection_create(JNIEnv *pEnv, jobject obj, jint version,
                                            jint iceTransportPolicy, 
                                            jstring stun_server_url, 
                                            jstring turn_server_url, jstring turn_username, jstring turn_credential, 
                                            jlong userptr);

// 函数说明:    释放PeerConnection
// 输入:  peer_connection, 由上面的create函数创建的PeerConnection对象
// 输出:  0: 成功   other: 失败
JNIEXPORT jint JNICALL Java_cn_easyrtc_peerconnection_release(JNIEnv* pEnv, jobject obj, jlong peer_connection);

// 函数说明:    创建transceiver, 返回transceiver, 对端的音视频数据通过回调函数OnEasyRTC_Transceiver_Callback回调给上层
//              public static int OnEasyRTC_Transceiver_Callback(long userPtr, int type, int codecId, int frameType, byte[] frameData, int frameSize, long pts, int bandwidthEstimation) 
//              {
//                      userPtr:    用户自定义值, 由AddTransceiver函数的最后一个参数传入
//                      type:    	EASYRTC_TRANSCEIVER_CALLBACK_VIDEO_FRAME = 0x01,// 回调视频帧数据
//                                  EASYRTC_TRANSCEIVER_CALLBACK_AUDIO_FRAME,		// 回调音频帧数据
//                                  EASYRTC_TRANSCEIVER_CALLBACK_BANDWIDTH,			// 回调带宽
//                                  EASYRTC_TRANSCEIVER_CALLBACK_KEY_FRAME_REQ,		// 请求关键帧
//                      codecId:    对端的音视频编码ID
//                      frameType:  帧类型(1: 关键帧   other:非关键帧)
//                      frameData:  帧数据
//                      frameSize:  帧大小
//                      pts:        时间戳
//                      bandwidthEstimation: 带宽
//              }
// 输入:      peerconnection, 由create创建的PeerConnection对象
//            codecID: 音视频编码ID, 列表如下:
//                          EasyRTC_CODEC_H264 = 1,						// H264
//                          EasyRTC_CODEC_OPUS = 2,						// OPUS
//                          EasyRTC_CODEC_VP8 = 3,						// VP8
//                          EasyRTC_CODEC_MULAW = 4,			        // MULAW
//                          EasyRTC_CODEC_ALAW = 5,						// ALAW
//                          EasyRTC_CODEC_H265 = 6,                     // H265
//                          EasyRTC_CODEC_AAC = 7,                      // AAC
//                          EasyRTC_CODEC_UNKNOWN = 8,
//              streamId: 流id(0)
//              trackId:  轨道id(0: 视频,  1: 音频)
//              streamTrackType: 轨道类型
//                          EasyRTC_MEDIA_STREAM_TRACK_KIND_AUDIO = 1, // 音频轨
//                          EasyRTC_MEDIA_STREAM_TRACK_KIND_VIDEO = 2, // 视频轨
//              direction:  传输模式
//                          EasyRTC_RTP_TRANSCEIVER_DIRECTION_SENDRECV = 1, // 发送&接收
//                          EasyRTC_RTP_TRANSCEIVER_DIRECTION_SENDONLY = 2, // 仅发送
//                          EasyRTC_RTP_TRANSCEIVER_DIRECTION_RECVONLY = 3, // 仅接收
//                          EasyRTC_RTP_TRANSCEIVER_DIRECTION_INACTIVE = 4, // 对端无法发送或接收数据
//              userptr:    用户自定义值，用于在回调时原样回调
// 输出:      Transceiver对象
JNIEXPORT jlong JNICALL Java_cn_easyrtc_peerconnection_AddTransceiver(JNIEnv* pEnv, jobject obj,
                                                            jlong peerconnection,
                                                            jint codecID, jstring streamId, jstring trackId, jint streamTrackType, jint direction, 
                                                            jlong userptr);

// 函数说明:    发送视频帧
// 输入:        transceiver: 由AddTransceiver创建的transceiver对象
//              framedata:   帧数据
//              framesize:   帧大小
//              keyframe:    是否为关键帧(1:关键帧, other:其它)
//              pts:         时间戳
// 输出:        0:成功  other: 失败
JNIEXPORT jint JNICALL Java_cn_easyrtc_peerconnection_SendVideoFrame(JNIEnv* pEnv, jobject obj, 
                                                            jlong transceiver,
                                                            jbyteArray framedata, jint framesize, jint keyframe, jint pts);


// 函数说明:    发送音频帧
// 输入:        transceiver: 由AddTransceiver创建的transceiver对象
//              framedata:   帧数据
//              framesize:   帧大小
//              pts:         时间戳
// 输出:        0:成功  other: 失败
JNIEXPORT jint JNICALL Java_cn_easyrtc_peerconnection_SendAudioFrame(JNIEnv* pEnv, jobject obj,
                                                            jlong transceiver,
                                                            jbyteArray framedata, jint framesize, jint pts);


// 函数说明:    删除transceiver
// 输入:       transceiver: 由AddTransceiver创建的transceiver对象
// 输出:        0:成功  other: 失败
JNIEXPORT jint JNICALL Java_cn_easyrtc_peerconnection_FreeTransceiver(JNIEnv* pEnv, jobject obj, jlong transceiver);


// 函数说明:    创建DataChannel, 返回DataChannel, 当前状态及对端发送的数据通过回调函数OnEasyRTC_DataChannel_Callback回调给上层
//              public static int OnEasyRTC_DataChannel_Callback(long userPtr, int type, int binary, String jstring, byte[] jbytearray, int size) 
//              {
//                      userPtr:    用户自定义值, 由CreateDataChannel函数的最后一个参数传入
//                      type:   
//                                  	EASYRTC_DATACHANNEL_CALLBACK_OPENED = 0x01,		// DataChannel 已打开
//                                      EASYRTC_DATACHANNEL_CALLBACK_DATA = 0x02,		// DataChannel 数据
//                      binary:     是否为二进制数据
//                      jstring:    binary为0时有效，表示为文本数据
//                      jbytearray: binary为1时有效, 表示为二进制数据
//                      size:       数据大小
//              }
// 输入:        peerconnection: 由create创建的PeerConnection对象
//              name:       名称
//              userptr:    用户自定义值，用于在回调时原样回调
// 输出:        DataChannel对象
JNIEXPORT jlong JNICALL Java_cn_easyrtc_peerconnection_AddDataChannel(JNIEnv* pEnv, jobject obj, jlong peerconnection,jstring name, jlong userptr);


// 函数说明:    通过DataChannel发送数据
// 输入:        data_channel: 由CreateDataChannel创建的DataChannel对象
//              isBinary:   是否为二进制数据
//              data_string: 如果isBinary为false时则发送该值给对端
//              data_binary: 如果isBinary为true时则发送该值给对端
//              size:   数据长度
// 输出:        0:成功  other: 失败
JNIEXPORT jint JNICALL Java_cn_easyrtc_peerconnection_DataChannelSend(JNIEnv* pEnv, jobject obj, 
                                                jlong data_channel,
                                                jint isBinary, jbyteArray data_binary, jint size);

// 函数说明:    释放DataChannel
// 输入:        data_channel: 由AddDataChannel创建的DataChannel对象
// 输出:        0:成功  other: 失败
JNIEXPORT jint JNICALL Java_cn_easyrtc_peerconnection_FreeDataChannel(JNIEnv* pEnv, jobject obj, jlong in_dataChannel);


// 函数说明:    创建Offer, sdp通过回调函数OnEasyRTC_IceCandidate_Callback给出,请参考OnEasyRTC_IceCandidate_Callback定义
//              public static int OnEasyRTC_IceCandidate_Callback(long userPtr, int isOffer, String sdp) 
//              {
//                      userPtr:    用户自定义值, 由CreateOffer函数的最后一个参数传入
//                      isOffer:    是否为offer的sdp, 1为offer的SDP, 0为answer的SDP
//                      sdp:        sdp数据
//              }
//  输入:       peerconnection: 由create创建的PeerConnection对象
//              userptr:    用户自定义值，用于在回调时原样回调
// 输出:        0:成功  other: 失败
JNIEXPORT jint JNICALL Java_cn_easyrtc_peerconnection_CreateOffer(JNIEnv* pEnv, jobject obj, jlong peerconnection, jlong userptr);


// 函数说明:    设置远端SDP:当本地为设备端时,本地创建了offer发给对端,待对端回复answer后调用EasyRTC_SetRemoteDescription
//  输入:       peerconnection: 由create创建的PeerConnection对象
//              sdp: 对端的sdp数据
// 输出:        0:成功  other: 失败
JNIEXPORT jint JNICALL Java_cn_easyrtc_peerconnection_SetRemoteDescription(JNIEnv* pEnv, jobject obj, jlong peerconnection, jstring sdp);



// 函数说明:    创建Answer:根据对端offer的sdp创建answer,sdp通过回调函数OnEasyRTC_IceCandidate_Callback给出,请参考OnEasyRTC_IceCandidate_Callback定义
//              public static int OnEasyRTC_IceCandidate_Callback(long userPtr, int isOffer, String sdp) 
//              {
//                      userPtr:    用户自定义值, 由CreateOffer函数的最后一个参数传入
//                      isOffer:    是否为offer的sdp, 1为offer的SDP, 0为answer的SDP
//                      sdp:        sdp数据
//              }
//  输入:       peerconnection: 由create创建的PeerConnection对象
//              offer_sdp:      对端的sdp数据
//              userptr:    用户自定义值，用于在回调时原样回调
// 输出:        0:成功  other: 失败

JNIEXPORT jint JNICALL Java_cn_easyrtc_peerconnection_CreateAnswer(JNIEnv* pEnv, jobject obj, jlong peerconnection, jstring offer_sdp, jlong userptr);

// 函数说明:    获取连接类型 (1为p2p, 2为relay)
//  输入:       peerconnection: 由create创建的PeerConnection对象
//  输出:       1:p2p  2: 转发  other: 获取失败(可能连接还未建立,所以需在回调函数OnEasyRTC_ConnectionStateChange_Callback的state为EASYRTC_PEER_CONNECTION_STATE_CONNECTED时调用
JNIEXPORT jint JNICALL Java_cn_easyrtc_peerconnection_GetIceCandidateType(JNIEnv* pEnv, jobject obj, jlong peerconnection);



#ifdef __cplusplus
}
#endif
#endif
